package com.tripfit.tripfit.common.logging;

public enum SocialIntegrationAction {
  LOGIN_TOKEN_VERIFY,
  LOGIN_USERINFO_FETCH,
  LOGIN_TOKEN_REVOKE,
  LOGIN_CREDENTIAL_EXCHANGE,
  LOGIN_CREDENTIAL_REVOKE,
  APPLE_NOTIFICATION_VERIFY,
  APPLE_NOTIFICATION_PROCESS,
  CALENDAR_CONNECT,
  CALENDAR_SYNC,
  CALENDAR_TOKEN_REVOKE
}
